<?php return array (
  'table' => 
  array (
    'article' => 
    array (
      'tablename' => 'article',
      'engine' => 'MyISAM',
      'rows' => '14',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '116',
      'indexSize' => '2048',
      'dataSize' => '2900',
      'totalSize' => 5064,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'attachment' => 
    array (
      'tablename' => 'attachment',
      'engine' => 'InnoDB',
      'rows' => '11',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '49152',
      'dataSize' => '16384',
      'totalSize' => 9502720,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'category' => 
    array (
      'tablename' => 'category',
      'engine' => 'MyISAM',
      'rows' => '12',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '2048',
      'dataSize' => '452',
      'totalSize' => 2500,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'config' => 
    array (
      'tablename' => 'config',
      'engine' => 'MyISAM',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '2048',
      'dataSize' => '180',
      'totalSize' => 2228,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'flash' => 
    array (
      'tablename' => 'flash',
      'engine' => 'MyISAM',
      'rows' => '5',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '100',
      'indexSize' => '2048',
      'dataSize' => '508',
      'totalSize' => 2656,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'keyword' => 
    array (
      'tablename' => 'keyword',
      'engine' => 'MyISAM',
      'rows' => '12',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '52',
      'indexSize' => '2048',
      'dataSize' => '484',
      'totalSize' => 2584,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'migrations' => 
    array (
      'tablename' => 'migrations',
      'engine' => 'MyISAM',
      'rows' => '10',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '1024',
      'dataSize' => '388',
      'totalSize' => 1412,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'module' => 
    array (
      'tablename' => 'module',
      'engine' => 'MyISAM',
      'rows' => '2',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '28',
      'indexSize' => '2048',
      'dataSize' => '280',
      'totalSize' => 2356,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'seeds' => 
    array (
      'tablename' => 'seeds',
      'engine' => 'MyISAM',
      'rows' => '2',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '1024',
      'dataSize' => '100',
      'totalSize' => 1124,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'user' => 
    array (
      'tablename' => 'user',
      'engine' => 'MyISAM',
      'rows' => '2',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '2048',
      'dataSize' => '1752',
      'totalSize' => 3800,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'weixinconfig' => 
    array (
      'tablename' => 'weixinconfig',
      'engine' => 'MyISAM',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '2048',
      'dataSize' => '296',
      'totalSize' => 2344,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'wxcontent' => 
    array (
      'tablename' => 'wxcontent',
      'engine' => 'MyISAM',
      'rows' => '7',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '2048',
      'dataSize' => '248',
      'totalSize' => 2296,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
  ),
  'config' => 
  array (
    'size' => 200,
    'dir' => 'backup/20170724073539',
  ),
);